export enum AuditAction {
  MEMBERSHIP_ROLE_CHANGED = 'MEMBERSHIP_ROLE_CHANGED',
  MEMBERSHIP_STATUS_CHANGED = 'MEMBERSHIP_STATUS_CHANGED',
  MEMBERSHIP_REMOVED = 'MEMBERSHIP_REMOVED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  ALL_SESSIONS_REVOKED = 'ALL_SESSIONS_REVOKED',
}
