export enum AuditAction {
  INSTITUTE_USER_ADDED = 'INSTITUTE_USER_ADDED',

  MEMBERSHIP_ROLE_CHANGED = 'MEMBERSHIP_ROLE_CHANGED',

  MEMBERSHIP_STATUS_CHANGED = 'MEMBERSHIP_STATUS_CHANGED',

  MEMBERSHIP_REMOVED = 'MEMBERSHIP_REMOVED',

  SESSION_REVOKED = 'SESSION_REVOKED',

  ALL_SESSIONS_REVOKED = 'ALL_SESSIONS_REVOKED',

  INSTITUTE_PROFILE_UPDATED = 'INSTITUTE_PROFILE_UPDATED',

  INSTITUTE_INVITATION_CREATED = 'INSTITUTE_INVITATION_CREATED',

  INSTITUTE_INVITATION_REVOKED = 'INSTITUTE_INVITATION_REVOKED',

  INSTITUTE_INVITATION_RESENT = 'INSTITUTE_INVITATION_RESENT',
}
